### ISSUE TITLE
make pypi and conda packages for 0.3.0

### ISSUE THREAD

**Issue by gidden** [iiasa/aneris#47]
- [x] pypi
- ~~[ ] conda~~

**Comment by gidden** [comment]
cc @khaeru - could we put this on a future support request please?

**Comment by khaeru** [comment]
> cc @khaeru - could we put this on a future support request please?

Sorry, I'm not sure what's meant by this. Do you want to assign me?

**Comment by gidden** [comment]
No, I don't want to assign you but rather put this on the docket for IIASA ECE dev ops support. Perhaps I should be cc'ing @danielhuppmann as well?

**Comment by khaeru** [comment]
Okay, understood. That can be broken down into two kinds of work:
1. Bringing the packaging, tooling, CI config, Slack integration, etc., for this repo in line with what we use across our other repos.
2. Ongoing maintenance.

For ixmp, message_ix, message-ix-models, and message_data, @LauWien and I have invested heavily in (1) to make them as uniform as possible. This eases (2) significantly, because the maintenance/updates/fixes can be applied by copy-paste (or nearly so); the same well-described release procedure works for all the repos, etc.

Depending on how active development is here, (2) is probably manageable in the long term (at least, it is not bigger than our other resource allocation problems). But (1) could be a sizeable chunk of work in the short term; it depends on the current state of the package, with which I'm not familiar. IMO it would be easiest if you (or someone you can find) approached (1) by copying from the other repos, and then asked us to review the result and continue with (2) once merged.

**Comment by gidden** [comment]
Thanks @khaeru - pinged the wrong group. Feel free to delegate as useful @danielhuppmann, thanks!

**Comment by jkikstra** [comment]
Great, thanks for this. 
Just commenting to keep up-to-date, such that I can merge in a PR on the climate-assessment repo when this is done

**Comment by gidden** [comment]
@jkikstra - latest `aneris` now on pip thanks to @danielhuppmann ! I couldn't find a conda-forge feedstock, so don't think it was ever there (which is fine).

**Comment by jkikstra** [comment]
Thank you @danielhuppmann and @gidden for notifying me, great!
